-- Oracle Schema for typedb examples
-- Run this to set up the example database

-- Create tables
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    content CLOB,
    tags CLOB, -- JSON stored as CLOB
    metadata CLOB, -- JSON stored as CLOB
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_posts (
    user_id NUMBER NOT NULL,
    post_id NUMBER NOT NULL,
    favorited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_posts PRIMARY KEY (user_id, post_id),
    CONSTRAINT fk_user_posts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_posts_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- Insert sample data
INSERT INTO users (name, email) VALUES ('Alice', 'alice@example.com');
INSERT INTO users (name, email) VALUES ('Bob', 'bob@example.com');
INSERT INTO users (name, email) VALUES ('Charlie', 'charlie@example.com');

INSERT INTO posts (user_id, title, content, tags, metadata) VALUES 
    (1, 'First Post', 'This is my first post', '["go", "database"]', '{"views": 10, "likes": 5}');
INSERT INTO posts (user_id, title, content, tags, metadata) VALUES 
    (1, 'Second Post', 'Another post', '["sql", "oracle"]', '{"views": 20, "likes": 8}');
INSERT INTO posts (user_id, title, content, tags, metadata) VALUES 
    (2, 'Hello World', 'Hello from Bob', '["hello"]', '{"views": 5, "likes": 2}');

INSERT INTO user_posts (user_id, post_id) VALUES (1, 1);
INSERT INTO user_posts (user_id, post_id) VALUES (1, 2);
INSERT INTO user_posts (user_id, post_id) VALUES (2, 3);

COMMIT;
