-- Create a separate table for LONG RAW type
-- Oracle allows only one LONG column per table, so we need a separate table
CREATE TABLE long_raw_examples (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    long_raw_col LONG RAW,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
