-- Create a comprehensive table demonstrating ALL Oracle data types
-- Note: Using a user tablespace to avoid SecureFiles LOB restrictions in SYSTEM tablespace
CREATE TABLE type_examples (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Numeric types
    number_col NUMBER,
    number_precision_col NUMBER(10, 2),
    number_scale_col NUMBER(38),
    float_col FLOAT,
    float_precision_col FLOAT(126),
    binary_float_col BINARY_FLOAT,
    binary_double_col BINARY_DOUBLE,
    
    -- Character types
    char_col CHAR(10),
    varchar2_col VARCHAR2(255),
    varchar_col VARCHAR(255),
    nchar_col NCHAR(10),
    nvarchar2_col NVARCHAR2(255),
    
    -- Large object types
    clob_col CLOB,
    nclob_col NCLOB,
    long_col LONG, -- Note: Oracle allows only one LONG column per table
    
    -- Binary types
    raw_col RAW(16),
    blob_col BLOB,
    bfile_col BFILE,
    
    -- Date/Time types
    date_col DATE,
    timestamp_col TIMESTAMP,
    timestamp_precision_col TIMESTAMP(6),
    timestamp_tz_col TIMESTAMP WITH TIME ZONE,
    timestamp_ltz_col TIMESTAMP WITH LOCAL TIME ZONE,
    interval_year_col INTERVAL YEAR TO MONTH,
    interval_day_col INTERVAL DAY TO SECOND,
    
    -- Row ID types
    rowid_col ROWID, -- ROWID is system-generated, can be selected but not inserted
    urowid_col UROWID,
    
    -- Large object types
    xmltype_col XMLTYPE,
    
    -- Created timestamp
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
