-- Insert sample users
INSERT INTO users (id, name, email) VALUES (1, 'Alice', 'alice@example.com');
INSERT INTO users (id, name, email) VALUES (2, 'Bob', 'bob@example.com');
INSERT INTO users (id, name, email) VALUES (3, 'Charlie', 'charlie@example.com');

-- Insert sample posts
INSERT INTO posts (id, user_id, title, content, tags, metadata) VALUES 
    (1, 1, 'First Post', 'This is my first post', '["go", "database"]', '{"views": 10, "likes": 5}');
INSERT INTO posts (id, user_id, title, content, tags, metadata) VALUES 
    (2, 1, 'Second Post', 'Another post', '["sql", "oracle"]', '{"views": 20, "likes": 8}');
INSERT INTO posts (id, user_id, title, content, tags, metadata) VALUES 
    (3, 2, 'Hello World', 'Hello from Bob', '["hello"]', '{"views": 5, "likes": 2}');

-- Insert sample user_posts relationships
INSERT INTO user_posts (user_id, post_id) VALUES (1, 1);
INSERT INTO user_posts (user_id, post_id) VALUES (1, 2);
INSERT INTO user_posts (user_id, post_id) VALUES (2, 3);

-- Reset identity sequences to start after the inserted data
-- This prevents unique constraint violations when tests insert new records
ALTER TABLE users MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 4 INCREMENT BY 1);
ALTER TABLE posts MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 4 INCREMENT BY 1);

COMMIT;
